Improve tests
AdrielVelazquez/sqlalchemy-sphinx pull request #10
Opened 2019-10-31 19:36 UTC by subnix

Tests have been improved and refactored.
3 bugs have been found:
1) Typo in dialect name;
2) cymysql's escape_value breaks match query;
3) Missing escape for percent char (printf-style formatting).

2020-12-01 09:26 UTC, subnix commented
Are there any updates?)

2020-12-03 00:20 UTC, AdrielVelazquez requested changes

2020-12-03 16:41 UTC, subnix commented on tests/test_dialects.py
> +        sql_text = query._compile_context().statement.compile(sphinx_engine).string
I have removed direct _compile_context usage.

2021-03-13 19:19 UTC, AdrielVelazquez approved these changes

2021-03-13 19:19 UTC, merged

2021-03-15 09:16 UTC, subnix commented
Could you update the PyPi package?